/**
 * Checked-in dictionary data (generated by scripts/convert-quickfix.mjs from
 * QuickFIX XML specs) with lazy loading: only the requested version's data
 * is pulled into the running bundle (FIX 5.0SP2 alone is ~0.5 MB raw).
 * Dynamic imports resolve to same-origin bundled chunks — no network.
 */
import type { Dictionary, FixVersionId } from '../types.ts';
import { dictionaryFromJson, type DictionaryJson } from '../json.ts';

const loaders: Record<FixVersionId, () => Promise<{ default: unknown }>> = {
  'FIX.4.2': () => import('./fix42.json'),
  'FIX.4.4': () => import('./fix44.json'),
  'FIX.5.0SP2': () => import('./fix50sp2.json'),
};

const cache = new Map<FixVersionId, Dictionary>();

export async function loadBaseDictionary(version: FixVersionId): Promise<Dictionary> {
  const cached = cache.get(version);
  if (cached) return cached;
  const module = await loaders[version]();
  const dict = dictionaryFromJson(module.default as DictionaryJson, version);
  cache.set(version, dict);
  return dict;
}
